### ISSUE TITLE
Update for new location of EDM installers

### ISSUE THREAD

**Issue by mdickinson** [enthought/setup-edm-action#2]
The URLs used to locate EDM installers for the newest versions have changed, and the URLs used in this action appear to be no longer valid for EDM versions past EDM 3.2.3.

I don't currently have a definitive answer to the question of whether there are future-proof URLs that we can use in place of the current ones.

**Comment by rahulporuri** [comment]
I'm not sure what the relationship between `https://package-data.enthought.com/edm/win_x86_64/*` URLs and `https://assets.enthought.com/downloads/installer/*` URLs is. We are trying to use the former and the latter is what is advertised on this page - https://assets.enthought.com/downloads/edm/

**Comment by mdickinson** [comment]
This is now resolved: the current URLs are valid again for new EDM releases, including the recently released EDM 3.2.5, but not EDM 3.2.4. (But I guess no-one will be asking for 3.2.4 when 3.2.5 is available, so this should be fine.)
